In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
csv_path = ("rides.csv")
df = pd.read_csv(csv_path, parse_dates = ['Started at','Finished at'])
df.head()

,ID,Vehicle ID,Status,Member,Member ID,Duration,Fare,Started at,Finished at,Member Type,Starting Parking Station Name,End Parking Station Name,Ride Distance,Starting Parking lot id,End Parking lot id
0,23737,28.0,finished,anjum shaik,11154,0:10:53,0,2019-01-13 21:22:00,2019-01-13 21:33:00,casual_user,"Yashodhan Nagar, Vartak Nagar, ठाणे, Thane, Ma...",R-Mall,1.9,NaN,15.0
1,23736,107.0,finished,shruthi d kamath,11689,0:21:58,0,2019-01-13 21:15:00,2019-01-13 21:37:00,casual_user,"Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",Highland Park,2.3,NaN,18.0
2,23735,22.0,finished,Ankit THAKUR,13558,0:09:38,0,2019-01-13 21:12:00,2019-01-13 21:22:00,casual_user,"Service Road, Kolse Wadi, Majiwada, ठाणे, Than...","Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",3.1,NaN,NaN
3,23734,171.0,finished,Ankit THAKUR,13558,0:01:12,0,2019-01-13 21:10:00,2019-01-13 21:11:00,casual_user,"Dr Kashinath Ghanekar Drama theatre, Gladys Al...","Dr Kashinath Ghanekar Drama theatre, Gladys Al...",0.0,NaN,NaN
4,23733,158.0,finished,asmita kadam,13761,0:24:08,0,2019-01-13 21:07:00,2019-01-13 21:31:00,casual_user,"Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",Highland Park,3.6,NaN,18.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14002 entries, 0 to 14001
Data columns (total 15 columns):
ID                               14002 non-null int64
Vehicle ID                       13567 non-null float64
Status                           14002 non-null object
Member                           13387 non-null object
Member ID                        14002 non-null int64
Duration                         14002 non-null object
Fare                             14002 non-null int64
Started at                       14002 non-null datetime64[ns]
Finished at                      14002 non-null datetime64[ns]
Member Type                      14002 non-null object
Starting Parking Station Name    13232 non-null object
End Parking Station Name         13249 non-null object
Ride Distance                    13925 non-null float64
Starting Parking lot id          9678 non-null float64
End Parking lot id               9946 non-null float64
dtypes: datetime64[ns](2), float64(4), int64(3), object(6)
memory usage: 1.6+ MB

### Looking for Unfinised rides

In [7]:
df[df.Status != 'finished']

Empty DataFrame
Columns: [ID, Vehicle ID, Status, Member, Member ID, Duration, Fare, Started at, Finished at, Member Type, Starting Parking Station Name, End Parking Station Name, Ride Distance, Starting Parking lot id, End Parking lot id]
Index: []

### Looking for Rides with duration less than a minute.

In [8]:
df['Duration'].loc[df.Duration < '0:01:00'].count() #6392 rides with duration less than a minute

6392

In [9]:
df.loc[df.Duration < '0:01:00']

,ID,Vehicle ID,Status,Member,Member ID,Duration,Fare,Started at,Finished at,Member Type,Starting Parking Station Name,End Parking Station Name,Ride Distance,Starting Parking lot id,End Parking lot id
7,23730,116.0,finished,Harish Nair,7846,0:00:42,0,2019-01-13 20:39:00,2019-01-13 20:40:00,casual_user,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...","Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",0.0,NaN,NaN
8,23729,28.0,finished,yaseen,8435,0:00:15,0,2019-01-13 20:33:00,2019-01-13 20:33:00,casual_user,"The Origin Fertility Clinic, Gladys Alwares Ro...",Kashinath Ghanekar,0.0,NaN,10.0
10,23727,239.0,finished,Rahul Sonsale,7796,0:00:32,0,2019-01-13 20:23:00,2019-01-13 20:24:00,casual_user,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",Tata Sirien,0.0,NaN,6.0
14,23723,64.0,finished,rhea duseja,11609,0:00:21,0,2019-01-13 20:05:00,2019-01-13 20:05:00,casual_user,"Tulsidham Road, Vartak Nagar, ठाणे, Thane, Mah...","Tulsidham Road, Vartak Nagar, ठाणे, Thane, Mah...",0.0,NaN,NaN
15,23722,64.0,finished,rhea duseja,11609,0:00:21,0,2019-01-13 20:03:00,2019-01-13 20:04:00,casual_user,Vasant Vihar,Vasant Vihar,0.0,9.0,9.0
17,23720,88.0,finished,Suresh,7950,0:00:15,0,2019-01-13 19:58:00,2019-01-13 19:59:00,casual_user,"Smt. Sulochanadevi Singhania School, Pokhran R...","Smt. Sulochanadevi Singhania School, Pokhran R...",0.0,NaN,NaN
25,23712,59.0,finished,Suresh,7950,0:00:19,0,2019-01-13 19:35:00,2019-01-13 19:35:00,casual_user,Singhania School,Singhania School,0.0,3.0,3.0
30,23707,70.0,finished,vikas pandurang kulkarni,13297,0:00:24,0,2019-01-13 19:16:00,2019-01-13 19:17:00,casual_user,"Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...",Patlipada,0.0,NaN,12.0
34,23702,153.0,finished,Sandeep Vora,13161,0:00:50,0,2019-01-13 19:10:00,2019-01-13 19:11:00,casual_user,Vartak Nagar,Vartak Nagar,0.0,2.0,2.0
41,23695,112.0,finished,Madhav Narayan Aarotale,7779,0:00:21,0,2019-01-13 18:42:00,2019-01-13 18:42:00,casual_user,"Service Road, Dnyaneshwar Nagar, Naupada, ठाणे...","Service Road, Dnyaneshwar Nagar, Naupada, ठाणे...",0.0,NaN,NaN
42,23694,79.0,finished,Madhav Narayan Aarotale,7779,0:00:14,0,2019-01-13 18:41:00,2019-01-13 18:42:00,casual_user,"Eastern Express Highway, Dnyaneshwar Nagar, Na...","Eastern Express Highway, Dnyaneshwar Nagar, Na...",0.0,NaN,NaN
43,23693,79.0,finished,Madhav Narayan Aarotale,7779,0:00:12,0,2019-01-13 18:41:00,2019-01-13 18:41:00,casual_user,"Eastern Express Highway, Dnyaneshwar Nagar, Na...",EEH Panchpakadi Entrence,0.0,NaN,21.0
44,23692,93.0,finished,Madhav Narayan Aarotale,7779,0:00:17,0,2019-01-13 18:40:00,2019-01-13 18:40:00,casual_user,"Dharmaveer Marg, Dnyaneshwar Nagar, Naupada, ठ...","Eastern Express Highway, Dnyaneshwar Nagar, Na...",0.0,NaN,NaN
46,23690,241.0,finished,Madhav Narayan Aarotale,7779,0:00:17,0,2019-01-13 18:39:00,2019-01-13 18:39:00,casual_user,"Yashodhan Nagar, Lokmanya Nagar, ठाणे, Thane, ...","Eastern Express Highway, Dnyaneshwar Nagar, Na...",1.6,NaN,NaN
47,23689,186.0,finished,Madhav Narayan Aarotale,7779,0:00:15,0,2019-01-13 18:39:00,2019-01-13 18:39:00,casual_user,"Service Road, Dnyaneshwar Nagar, Naupada, ठाणे...","Eastern Express Highway, Dnyaneshwar Nagar, Na...",0.0,NaN,NaN
48,23688,153.0,finished,Rajendra Salvi,5671,0:00:43,0,2019-01-13 18:38:00,2019-01-13 18:39:00,casual_user,Vartak Nagar,Vartak Nagar,0.0,2.0,2.0
49,23687,96.0,finished,Madhav Narayan Aarotale,7779,0:00:22,0,2019-01-13 18:37:00,2019-01-13 18:38:00,casual_user,"Dharmaveer Marg, Dnyaneshwar Nagar, Naupada, ठ...","Eastern Express Highway, Dnyaneshwar Nagar, Na...",0.0,NaN,NaN
54,23682,96.0,finished,Madhav Narayan Aarotale,7779,0:00:53,0,2019-01-13 18:17:00,2019-01-13 18:18:00,casual_user,ILC Warehouse,ILC Warehouse,0.0,13.0,13.0
55,23681,186.0,finished,Madhav Narayan Aarotale,7779,0:00:17,0,2019-01-13 18:11:00,2019-01-13 18:11:00,casual_user,"Yashodhan Nagar, Lokmanya Nagar, ठाणे, Thane, ...","Yashodhan Nagar, Lokmanya Nagar, ठाणे, Thane, ...",0.0,NaN,NaN
57,23679,120.0,finished,Madhav Narayan Aarotale,7779,0:00:14,0,2019-01-13 18:07:00,2019-01-13 18:08:00,casual_user,ILC Warehouse,ILC Warehouse,0.0,13.0,13.0
59,23677,84.0,finished,Syed Muddassir Ahmed,7781,0:00:23,0,2019-01-13 18:04:00,2019-01-13 18:04:00,casual_user,Shivai Nagar,Shivai Nagar,0.0,14.0,14.0
63,23673,106.0,finished,Syed Muddassir Ahmed,7781,0:00:14,0,2019-01-13 17:49:00,2019-01-13 17:49:00,casual_user,"Upvan Lake Road, Yashodhan Nagar, Shivai Nagar...",Shivai Nagar,0.0,NaN,14.0
69,23667,116.0,finished,Rahul Sonsale,7796,0:00:38,0,2019-01-13 17:36:00,2019-01-13 17:37:00,casual_user,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",Tata Sirien,0.0,NaN,6.0
70,23666,116.0,finished,Rahul Sonsale,7796,0:00:25,0,2019-01-13 17:36:00,2019-01-13 17:36:00,casual_user,Tata Sirien,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",0.0,6.0,NaN
71,23665,116.0,finished,Rahul Sonsale,7796,0:00:34,0,2019-01-13 17:34:00,2019-01-13 17:34:00,casual_user,Tata Sirien,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",0.0,6.0,NaN
72,23664,79.0,finished,Madhav Narayan Aarotale,7779,0:00:34,0,2019-01-13 17:32:00,2019-01-13 17:32:00,casual_user,ILC Warehouse,ILC Warehouse,0.0,13.0,13.0
73,23663,112.0,finished,Madhav Narayan Aarotale,7779,0:00:28,0,2019-01-13 17:30:00,2019-01-13 17:30:00,casual_user,"Yashodhan Nagar, Lokmanya Nagar, ठाणे, Thane, ...",ILC Warehouse,0.0,NaN,13.0
74,23662,93.0,finished,Madhav Narayan Aarotale,7779,0:00:31,0,2019-01-13 17:29:00,2019-01-13 17:29:00,casual_user,ILC Warehouse,"Yashodhan Nagar, Lokmanya Nagar, ठाणे, Thane, ...",0.0,13.0,NaN
87,23649,242.0,finished,Rahul Talawadekar,13754,0:00:49,0,2019-01-13 15:41:00,2019-01-13 15:42:00,casual_user,"Korum Mall, Service Road, Dnyaneshwar Nagar, N...","Korum Mall, Service Road, Dnyaneshwar Nagar, N...",0.1,NaN,NaN
88,23648,242.0,finished,Rahul Talawadekar,13754,0:00:33,0,2019-01-13 15:39:00,2019-01-13 15:39:00,casual_user,"Korum Mall, Service Road, Dnyaneshwar Nagar, N...","Korum Mall, Service Road, Dnyaneshwar Nagar, N...",0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13565,10171,82.0,finished,Srinidhi,12,0:00:41,0,2018-10-15 09:20:00,2018-10-15 09:21:00,casual_user,ILC Warehouse,ILC Warehouse,0.0,13.0,13.0
13587,10149,NaN,finished,Janardhan Mane,7369,0:00:22,0,2018-09-25 07:06:00,2018-09-25 07:06:00,casual_user,NaN,NaN,0.0,NaN,NaN
13591,10145,NaN,finished,Sailesh Sharma,4091,0:00:18,0,2018-09-24 18:23:00,2018-09-24 18:24:00,casual_user,NaN,NaN,NaN,NaN,NaN
13641,10094,NaN,finished,Sagar,7336,0:00:27,0,2018-09-20 21:35:00,2018-09-20 21:36:00,casual_user,NaN,NaN,0.2,NaN,NaN
13648,10087,NaN,finished,Suresh,7279,0:00:49,0,2018-09-20 14:28:00,2018-09-20 14:28:00,casual_user,NaN,NaN,1.1,NaN,NaN
13666,10069,NaN,finished,Arun Pendharkar,3379,0:00:16,0,2018-09-19 18:30:00,2018-09-19 18:30:00,casual_user,NaN,NaN,NaN,NaN,NaN
13669,10066,NaN,finished,Tanaji bhansode,4867,0:00:11,0,2018-09-19 17:15:00,2018-09-19 17:16:00,casual_user,NaN,NaN,0.0,NaN,NaN
13674,10061,NaN,finished,Avinash Sawant,5260,0:00:23,0,2018-09-18 20:32:00,2018-09-18 20:33:00,casual_user,NaN,NaN,0.1,NaN,NaN
13689,10046,NaN,finished,Arundeep Pathania,2131,0:00:24,0,2018-09-18 06:45:00,2018-09-18 06:45:00,casual_user,NaN,NaN,1.6,NaN,NaN
13719,10016,NaN,finished,Arun Mukesh,7332,0:00:12,0,2018-09-15 19:31:00,2018-09-15 19:32:00,casual_user,NaN,NaN,0.1,NaN,NaN
13730,10005,NaN,finished,Ajay Soni,6218,0:00:48,0,2018-09-15 07:21:00,2018-09-15 07:22:00,casual_user,NaN,NaN,NaN,NaN,NaN
13732,10003,NaN,finished,Srinidhi,12,0:00:52,0,2018-09-14 19:15:00,2018-09-14 19:16:00,casual_user,NaN,NaN,0.0,NaN,NaN
13737,9998,NaN,finished,Komal heffa,6997,0:00:14,0,2018-09-14 14:31:00,2018-09-14 14:31:00,casual_user,NaN,NaN,0.0,NaN,NaN
13757,9978,NaN,finished,Rupesh,7410,0:00:45,0,2018-09-13 09:26:00,2018-09-13 09:27:00,casual_user,NaN,NaN,0.4,NaN,NaN
13802,9933,NaN,finished,Mary Baby,4911,0:00:14,0,2018-10-09 18:54:00,2018-10-09 18:55:00,casual_user,NaN,NaN,0.0,NaN,NaN
13803,9932,NaN,finished,Mary Baby,4911,0:00:27,0,2018-10-09 18:52:00,2018-10-09 18:52:00,casual_user,NaN,NaN,0.0,NaN,NaN
13858,9874,NaN,finished,Pravin Lad,7179,0:00:11,0,2018-08-09 18:38:00,2018-08-09 18:38:00,casual_user,NaN,NaN,NaN,NaN,NaN
13860,9872,NaN,finished,Sonia Dembla,6326,0:00:45,0,2018-08-09 18:30:00,2018-08-09 18:31:00,casual_user,NaN,NaN,230.6,NaN,NaN
13869,9863,NaN,finished,Rajendra Salvi,5671,0:00:16,0,2018-08-09 07:28:00,2018-08-09 07:29:00,casual_user,NaN,NaN,0.3,NaN,NaN
13877,9855,NaN,finished,NaN,7439,0:00:45,0,2018-08-09 06:19:00,2018-08-09 06:20:00,casual_user,NaN,NaN,NaN,NaN,NaN
13890,9842,NaN,finished,Sangita Dalvi,6493,0:00:23,0,2018-07-09 08:32:00,2018-07-09 08:32:00,casual_user,NaN,NaN,0.1,NaN,NaN
13897,9835,NaN,finished,Srinidhi,12,0:00:33,0,2018-07-09 07:10:00,2018-07-09 07:11:00,casual_user,NaN,NaN,0.0,NaN,NaN
13906,9826,NaN,finished,Sailesh Ambre,2299,0:00:00,-200,2018-06-09 18:20:00,2018-06-09 18:20:00,casual_user,NaN,NaN,1.6,NaN,NaN
13911,9821,NaN,finished,Janardhan Mane,7369,0:00:11,0,2018-06-09 07:43:00,2018-06-09 07:43:00,casual_user,NaN,NaN,NaN,NaN,NaN
13912,9820,NaN,finished,Janardhan Mane,7369,0:00:12,0,2018-06-09 07:42:00,2018-06-09 07:42:00,casual_user,NaN,NaN,0.0,NaN,NaN
13935,9797,NaN,finished,Praveen Kumar,7343,0:00:00,-20,2018-04-09 15:50:00,2018-04-09 15:50:00,casual_user,NaN,NaN,2.7,NaN,NaN
13945,9787,NaN,finished,Avijit Chowdhury,5556,0:00:14,0,2018-03-09 18:41:00,2018-03-09 18:41:00,casual_user,NaN,NaN,1.7,NaN,NaN
13954,9778,NaN,finished,Janardhan Mane,7369,0:00:17,0,2018-03-09 06:55:00,2018-03-09 06:55:00,casual_user,NaN,NaN,0.0,NaN,NaN
13970,9762,NaN,finished,Janardhan Mane,7369,0:00:13,0,2018-02-09 08:57:00,2018-02-09 08:57:00,casual_user,NaN,NaN,0.1,NaN,NaN
14000,9732,NaN,finished,Janardhan Mane,7369,0:00:12,0,2018-01-09 07:22:00,2018-01-09 07:22:00,casual_user,NaN,NaN,0.0,NaN,NaN

### Dropping rides with duration less than a minute

In [10]:
new_df = df.drop(df[df.Duration < '0:01:00'].index)
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7610 entries, 0 to 14001
Data columns (total 15 columns):
ID                               7610 non-null int64
Vehicle ID                       7204 non-null float64
Status                           7610 non-null object
Member                           7234 non-null object
Member ID                        7610 non-null int64
Duration                         7610 non-null object
Fare                             7610 non-null int64
Started at                       7610 non-null datetime64[ns]
Finished at                      7610 non-null datetime64[ns]
Member Type                      7610 non-null object
Starting Parking Station Name    7040 non-null object
End Parking Station Name         7030 non-null object
Ride Distance                    7539 non-null float64
Starting Parking lot id          5146 non-null float64
End Parking lot id               5321 non-null float64
dtypes: datetime64[ns](2), float64(4), int64(3), object(6)
memory usage: 951.2+ KB

In [11]:
new_df.loc[new_df['Ride Distance'] == 0]

,ID,Vehicle ID,Status,Member,Member ID,Duration,Fare,Started at,Finished at,Member Type,Starting Parking Station Name,End Parking Station Name,Ride Distance,Starting Parking lot id,End Parking lot id
3,23734,171.0,finished,Ankit THAKUR,13558,0:01:12,0,2019-01-13 21:10:00,2019-01-13 21:11:00,casual_user,"Dr Kashinath Ghanekar Drama theatre, Gladys Al...","Dr Kashinath Ghanekar Drama theatre, Gladys Al...",0.0,NaN,NaN
22,23715,212.0,finished,Syed Muddassir Ahmed,7781,0:01:09,0,2019-01-13 19:46:00,2019-01-13 19:47:00,casual_user,Vartak Nagar,Vartak Nagar,0.0,2.0,2.0
23,23714,153.0,finished,Syed Muddassir Ahmed,7781,0:02:43,0,2019-01-13 19:40:00,2019-01-13 19:43:00,casual_user,Vartak Nagar,Vartak Nagar,0.0,2.0,2.0
35,23701,241.0,finished,eknath supadu nemade,12238,3:16:06,85,2019-01-13 19:06:00,2019-01-13 22:22:00,casual_user,"Eastern Express Highway, Dnyaneshwar Nagar, Na...","Service Road, Dnyaneshwar Nagar, Naupada, ठाणे...",0.0,NaN,NaN
37,23699,107.0,finished,NaN,12874,0:01:33,0,2019-01-13 18:55:00,2019-01-13 18:56:00,casual_user,"Agra Road, Kolse Wadi, Kapur Bawadi, ठाणे, Tha...","Agra Road, Kolse Wadi, Kapur Bawadi, ठाणे, Tha...",0.0,NaN,NaN
56,23680,106.0,finished,Syed Muddassir Ahmed,7781,0:01:20,0,2019-01-13 18:08:00,2019-01-13 18:10:00,casual_user,Shivai Nagar,"Upvan Lake Road, Yashodhan Nagar, Shivai Nagar...",0.0,14.0,NaN
60,23676,84.0,finished,Syed Muddassir Ahmed,7781,0:01:04,0,2019-01-13 18:02:00,2019-01-13 18:03:00,casual_user,Shivai Nagar,Shivai Nagar,0.0,14.0,14.0
67,23669,106.0,finished,Praveen Kumar,7343,0:03:28,0,2019-01-13 17:40:00,2019-01-13 17:43:00,casual_user,"Upvan Lake Road, Yashodhan Nagar, Shivai Nagar...","Upvan Lake Road, Yashodhan Nagar, Shivai Nagar...",0.0,NaN,NaN
82,23654,209.0,finished,jayesh sanjay gupta,13017,0:08:27,0,2019-01-13 16:50:00,2019-01-13 16:59:00,subscribed_user,"Kranti Nagar, Thane West, ठाणे, Thane, Maharas...","Kranti Nagar, Thane West, ठाणे, Thane, Maharas...",0.0,NaN,NaN
84,23652,128.0,finished,Praveen Kumar,7343,0:04:19,0,2019-01-13 16:34:00,2019-01-13 16:38:00,casual_user,ILC Warehouse,ILC Warehouse,0.0,13.0,13.0
107,23629,181.0,finished,Manohar,8532,0:02:35,0,2019-01-13 13:41:00,2019-01-13 13:44:00,casual_user,"The Origin Fertility Clinic, Gladys Alwares Ro...",Kashinath Ghanekar,0.0,NaN,10.0
149,23587,209.0,finished,Madhav shivajirao waghchaure,13551,1:47:19,25,2019-01-13 08:24:00,2019-01-13 10:11:00,subscribed_user,Collector's Office,Collector's Office,0.0,27.0,27.0
151,23585,70.0,finished,yaseen,8435,0:01:57,0,2019-01-13 08:18:00,2019-01-13 08:20:00,casual_user,"Hiranandani Estate, Brahmand Nagar, ठाणे, Than...","Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...",0.0,NaN,NaN
156,23580,114.0,finished,Amol Chaudhary,8060,0:01:08,0,2019-01-13 08:15:00,2019-01-13 08:16:00,casual_user,Kashinath Ghanekar,Kashinath Ghanekar,0.0,10.0,10.0
169,23567,104.0,finished,Vinodkumar.Pp,13757,0:03:35,0,2019-01-13 07:51:00,2019-01-13 07:55:00,casual_user,"Happy Valley Homes, Gladys Alwares Road, Kolse...","SBI, Gladys Alwares Road, Kolse Wadi, Vartak N...",0.0,NaN,NaN
185,23551,84.0,finished,shreekant salunkhe,12033,0:01:22,0,2019-01-13 06:53:00,2019-01-13 06:54:00,casual_user,Highland Park,Highland Park,0.0,18.0,18.0
188,23548,2.0,finished,Rakesh Desai,10419,2:16:22,45,2019-01-13 06:40:00,2019-01-13 08:56:00,casual_user,Singhania School,Singhania School,0.0,3.0,3.0
215,23521,92.0,finished,vandana kisan gawade,13214,0:07:54,0,2019-12-01 19:40:00,2019-12-01 19:47:00,casual_user,"Gadkari Rangayatan, Dr. Moose Road, Chendani K...",Goodwin Jewellers,0.0,NaN,22.0
224,23512,175.0,finished,Rupesh,7798,0:02:01,0,2019-12-01 19:15:00,2019-12-01 19:17:00,casual_user,Vihang Hotel,Vihang Hotel,0.0,16.0,16.0
245,23491,244.0,finished,Pravin bhachu gami,12427,0:01:10,0,2019-12-01 18:29:00,2019-12-01 18:30:00,casual_user,Tata Sirien,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",0.0,6.0,NaN
248,23488,92.0,finished,Alex,10423,0:01:04,0,2019-12-01 18:26:00,2019-12-01 18:27:00,casual_user,"Chendani Koliwada, Naupada, ठाणे, Thane, Mahar...","Ahilyadevi Holkar Marg, Chendani Koliwada, Tha...",0.0,NaN,NaN
254,23482,239.0,finished,pradnya bhori,11572,0:02:31,0,2019-12-01 18:20:00,2019-12-01 18:23:00,casual_user,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",Tata Sirien,0.0,NaN,6.0
266,23470,115.0,finished,Rahul Sonsale,7796,0:01:00,0,2019-12-01 17:46:00,2019-12-01 17:47:00,casual_user,"Lal Bahadur Shastri Marg, Kolse Wadi, Majiwada...",Majiwada,0.0,NaN,5.0
269,23467,212.0,finished,Madhav Narayan Aarotale,7779,0:01:21,0,2019-12-01 17:43:00,2019-12-01 17:44:00,casual_user,ILC Warehouse,ILC Warehouse,0.0,13.0,13.0
272,23464,244.0,finished,Amol,9501,0:01:09,0,2019-12-01 17:38:00,2019-12-01 17:39:00,casual_user,Tata Sirien,Tata Sirien,0.0,6.0,6.0
281,23455,175.0,finished,Aniket,1756,0:04:25,0,2019-12-01 16:57:00,2019-12-01 17:01:00,casual_user,"Bombay Barbeque, Service Road, Dnyaneshwar Nag...","Bombay Barbeque, Service Road, Dnyaneshwar Nag...",0.0,NaN,NaN
282,23454,81.0,finished,Rupesh,7798,0:02:43,0,2019-12-01 16:45:00,2019-12-01 16:48:00,casual_user,Vartak Nagar,Vartak Nagar,0.0,2.0,2.0
299,23437,25.0,finished,Raj Iyer,4691,0:04:40,0,2019-12-01 12:47:00,2019-12-01 12:52:00,casual_user,"Korum Mall, Service Road, Dnyaneshwar Nagar, N...","Korum Mall, Service Road, Dnyaneshwar Nagar, N...",0.0,NaN,NaN
305,23431,154.0,finished,Rupesh,7798,0:01:42,0,2019-12-01 12:26:00,2019-12-01 12:27:00,casual_user,"Patlipada RTO, Thane Ghodbunder Road, Brahmand...","Patlipada RTO, Thane Ghodbunder Road, Brahmand...",0.0,NaN,NaN
312,23424,78.0,finished,NaN,4569,0:01:16,0,2019-12-01 11:24:00,2019-12-01 11:25:00,casual_user,ILC Warehouse,"Yashodhan Nagar, Lokmanya Nagar, ठाणे, Thane, ...",0.0,13.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13517,10219,95.0,finished,soham,7804,0:01:38,0,2018-10-16 12:13:00,2018-10-16 12:14:00,casual_user,ILC Warehouse,ILC Warehouse,0.0,13.0,13.0
13520,10216,95.0,finished,soham,7804,0:01:16,0,2018-10-16 12:10:00,2018-10-16 12:11:00,casual_user,ILC Warehouse,ILC Warehouse,0.0,13.0,13.0
13522,10214,118.0,finished,Rupesh,7798,0:01:42,0,2018-10-16 12:07:00,2018-10-16 12:08:00,casual_user,NaN,ILC Warehouse,0.0,NaN,13.0
13531,10205,157.0,finished,Rupali Tulaskarr,4205,0:21:01,0,2018-10-16 07:49:00,2018-10-16 08:10:00,casual_user,NaN,Tata Sirien,0.0,NaN,6.0
13536,10200,110.0,finished,Syed Muddassir Ahmed,7781,0:01:00,0,2018-10-15 19:30:00,2018-10-15 19:31:00,casual_user,Vartak Nagar,Vartak Nagar,0.0,2.0,2.0
13542,10194,114.0,finished,Syed Muddassir Ahmed,7781,0:01:04,0,2018-10-15 19:21:00,2018-10-15 19:22:00,casual_user,Vartak Nagar,Vartak Nagar,0.0,2.0,2.0
13545,10191,154.0,finished,Rutvij Waze,7785,23:39:22,525,2018-10-15 17:49:00,2018-10-16 17:28:00,casual_user,NaN,NaN,0.0,NaN,NaN
13546,10190,82.0,finished,Syed Muddassir Ahmed,7781,0:01:08,0,2018-10-15 13:49:00,2018-10-15 13:51:00,casual_user,ILC Warehouse,ILC Warehouse,0.0,13.0,13.0
13553,10183,82.0,finished,Syed Muddassir Ahmed,7781,0:01:10,0,2018-10-15 12:16:00,2018-10-15 12:17:00,casual_user,Gandhi Nagar,Gandhi Nagar,0.0,8.0,8.0
13566,10170,82.0,finished,Srinidhi,12,0:02:02,0,2018-10-15 08:46:00,2018-10-15 08:48:00,casual_user,ILC Warehouse,ILC Warehouse,0.0,13.0,13.0
13603,10133,NaN,finished,Shashank Ziman,3382,0:10:49,0,2018-09-23 19:34:00,2018-09-23 19:44:00,casual_user,NaN,NaN,0.0,NaN,NaN
13611,10125,NaN,finished,Sanjana Amberkar,3663,0:11:02,0,2018-09-23 08:46:00,2018-09-23 08:57:00,casual_user,NaN,NaN,0.0,NaN,NaN
13626,10109,NaN,finished,Mary Baby,4911,0:24:36,0,2018-09-22 17:15:00,2018-09-22 17:40:00,casual_user,NaN,NaN,0.0,NaN,NaN
13693,10042,NaN,finished,JIgna Patil,5096,0:06:31,0,2018-09-17 19:54:00,2018-09-17 20:00:00,casual_user,NaN,NaN,0.0,NaN,NaN
13710,10025,NaN,finished,Rukmani Borude,5850,0:19:48,0,2018-09-16 18:04:00,2018-09-16 18:24:00,casual_user,NaN,NaN,0.0,NaN,NaN
13720,10015,NaN,finished,Jagathesan NB,7473,0:21:08,0,2018-09-15 19:29:00,2018-09-15 19:50:00,casual_user,NaN,NaN,0.0,NaN,NaN
13726,10009,NaN,finished,Janardhan Mane,7369,0:14:16,0,2018-09-15 08:52:00,2018-09-15 09:06:00,casual_user,NaN,NaN,0.0,NaN,NaN
13751,9984,NaN,finished,Rukmani Borude,5850,0:28:14,0,2018-09-13 17:58:00,2018-09-13 18:26:00,casual_user,NaN,NaN,0.0,NaN,NaN
13758,9977,NaN,finished,Rupesh,7410,0:50:39,10,2018-09-13 08:34:00,2018-09-13 09:25:00,casual_user,NaN,NaN,0.0,NaN,NaN
13766,9969,NaN,finished,Rukmani Borude,5850,0:22:41,0,2018-12-09 18:10:00,2018-12-09 18:32:00,casual_user,NaN,NaN,0.0,NaN,NaN
13773,9962,NaN,finished,Ramakanta Soni,4173,0:11:55,0,2018-12-09 07:45:00,2018-12-09 07:57:00,casual_user,NaN,NaN,0.0,NaN,NaN
13789,9946,NaN,finished,Rupesh,7410,0:07:02,0,2018-11-09 08:19:00,2018-11-09 08:27:00,casual_user,NaN,NaN,0.0,NaN,NaN
13846,9888,NaN,finished,Janardhan Mane,7369,0:35:17,10,2018-09-09 06:57:00,2018-09-09 07:33:00,casual_user,NaN,NaN,0.0,NaN,NaN
13856,9878,NaN,finished,Pravin Lad,7179,0:27:35,0,2018-08-09 19:11:00,2018-08-09 19:39:00,casual_user,NaN,NaN,0.0,NaN,NaN
13898,9834,NaN,finished,Ramakanta Soni,4173,0:15:48,0,2018-07-09 07:05:00,2018-07-09 07:21:00,casual_user,NaN,NaN,0.0,NaN,NaN
13903,9829,NaN,finished,Amit Karande,3900,0:03:53,0,2018-06-09 18:42:00,2018-06-09 18:46:00,casual_user,NaN,NaN,0.0,NaN,NaN
13947,9785,NaN,finished,Satyam Panigrahi,2759,0:17:08,0,2018-03-09 17:57:00,2018-03-09 18:14:00,casual_user,NaN,NaN,0.0,NaN,NaN
13960,9772,NaN,finished,Sonali Kadam,7019,0:22:29,0,2018-02-09 19:29:00,2018-02-09 19:52:00,casual_user,NaN,NaN,0.0,NaN,NaN
13966,9766,NaN,finished,Rukmani Borude,5850,0:26:20,0,2018-02-09 18:02:00,2018-02-09 18:28:00,casual_user,NaN,NaN,0.0,NaN,NaN
13971,9761,NaN,finished,Amit Karande,3900,1:29:51,15,2018-02-09 08:44:00,2018-02-09 10:14:00,casual_user,NaN,NaN,0.0,NaN,NaN

### Dropping values with Ride Distances that are 0 and greater than 76

In [12]:
df1 = new_df.drop(new_df[new_df['Ride Distance'] > 76].index)

In [13]:
df1 = new_df.drop(new_df[new_df['Ride Distance'] == 0].index)

In [164]:
bla = df1.loc[df1['Year'] == 2019]

In [165]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(bla)

         ID  Vehicle ID    Status                            Member  \
0     23737        28.0  finished                       anjum shaik
1     23736       107.0  finished                  shruthi d kamath
2     23735        22.0  finished                     Ankit THAKUR
4     23733       158.0  finished                     asmita kadam
5     23732       107.0  finished                    Rohan D kamath
6     23731       244.0  finished                       Harish Nair
9     23728        21.0  finished                             Tanvi
11    23726       105.0  finished                 suma latha shetty
12    23725       106.0  finished                     Shweta Ambade
13    23724       153.0  finished                     Rahul Sonsale
16    23721        64.0  finished                       rhea duseja
18    23719       186.0  finished        pradeep balkrishna shinde
19    23718       239.0  finished          bhavisha vikram doevkar
20    23717       158.0  finished                       kusum  jain
21    23716       176.0  finished                    Rajendra Salvi
24    23713       112.0  finished        pradeep balkrishna shinde
26    23711       231.0  finished                      Sandeep Vora
27    23710       158.0  finished                       kusum  jain
28    23709       117.0  finished                Piyush kumar raval
29    23708        70.0  finished         vikas pandurang kulkarni
31    23706        77.0  finished               jitendra kumar giri
32    23704       201.0  finished                     shamim shaik
33    23703       153.0  finished                      Sandeep Vora
36    23700       107.0  finished                               NaN
38    23698       107.0  finished                               NaN
39    23697       131.0  finished               sunil kumar trivedi
40    23696        77.0  finished               jitendra kumar giri
45    23691       176.0  finished                    Rajendra Salvi
50    23686        74.0  finished                     Praveen Kumar
51    23685       222.0  finished                     Shivam Tiwari
52    23684       214.0  finished                     Nilesh Mittal
53    23683       117.0  finished             bhaskar roy chowdhury
58    23678       201.0  finished                           Santosh
61    23675       158.0  finished                       kusum  jain
62    23674        74.0  finished                     Praveen Kumar
64    23672       181.0  finished                      Deepak Gupta
65    23671       219.0  finished                ashutosh kumar jha
66    23670        74.0  finished                     Praveen Kumar
68    23668       158.0  finished                       kusum  jain
75    23661       120.0  finished           Madhav Narayan Aarotale
76    23660       210.0  finished             santosh goroba dhage
77    23659        81.0  finished             santosh goroba dhage
78    23658        70.0  finished                  Shrirang dabhade
79    23657        35.0  finished                    jagruti thakur
80    23656       234.0  finished               jayesh sanjay gupta
81    23655       234.0  finished               jayesh sanjay gupta
83    23653        35.0  finished                    jagruti thakur
85    23651       153.0  finished                     Praveen Kumar
86    23650       193.0  finished                 Rahul Talawadekar
108   23628        35.0  finished           sumit parmanand sharma
109   23627        92.0  finished                     Praveen Kumar
110   23626        93.0  finished                           Sandeep
111   23625       241.0  finished               Harshvardhan Jadhav
112   23624       158.0  finished                             Vivek
113   23623       219.0  finished                      umesh patill
114   23622        70.0  finished                      Sameeha Sule
115   23621       106.0  finished                      Sayali Khare
117   23619         4.0  finished                            Sachin
118   23618        22.0  finished           Madhav Narayan Aarotale
119   23617        78.0  finished                       Anil Gaiwad
123   23613        84.0  finished                             soham
124   23612        28.0  finished                         Omprakash
129   23607       131.0  finished                            Ashish
130   23606        77.0  finished         chandrakala mahendra sing
131   23605       114.0  finished                      Vikram Meena
132   23604        28.0  finished                   minnjal harsora
133   23603       244.0  finished                            Mayank
134   23602       107.0  finished             sanskar sanjay bolkar
137   23599       184.0  finished                     Ankit THAKUR
138   23598       117.0  finished                     bharati kumar
139   23597       146.0  finished            pratap ,mahadev rasam
140   23596       131.0  finished        gundappa basavaraj tarapur
141   23595         4.0  finished             CHANDRABHUSHAN TIWARI
143   23593        77.0  finished         chandrakala mahendra sing
144   23592        92.0  finished                    praveen jolly
146   23590       104.0  finished                               NaN
148   23588       107.0  finished                           Khushru
150   23586        77.0  finished                     Santosh Kumar
152   23584       106.0  finished                     Amit Deshmukh
154   23582       114.0  finished                    Amol Chaudhary
155   23581       146.0  finished           rahul pratap sinha rane
158   23578       104.0  finished                     Vinodkumar.Pp
159   23577       157.0  finished                            Suresh
160   23576        93.0  finished                   Rucha Borwankar
161   23575       117.0  finished                               NaN
162   23574       193.0  finished       gayadin mahadev vishwakarma
163   23573        92.0  finished                    rajesh damodar
164   23572        77.0  finished                             soham
166   23570       210.0  finished                    Rajendra Salvi
167   23569        77.0  finished                             soham
170   23566       114.0  finished                       aneesh rege
171   23565       182.0  finished             jayesh sopan phadtare
172   23564       146.0  finished                     Harjeet Singh
173   23563        93.0  finished             sandeep ganpat bangar
174   23562       131.0  finished                  Yogesh aakoshkar
176   23560       201.0  finished                  jagdish p singh
178   23558        92.0  finished                    rajesh damodar
179   23557        28.0  finished                      neeraj kumar
180   23556       117.0  finished              geeta ganesh vidwans
181   23555       104.0  finished                     babita mishra
182   23554        92.0  finished                   Dharamraj Yadav
183   23553       210.0  finished                    Rajendra Salvi
184   23552        84.0  finished                shreekant salunkhe
186   23550        92.0  finished          JIGNESH KHIMRAJ RHAMBIA
187   23549       146.0  finished              PrashanT Sopan Patil
189   23547        14.0  finished                 raksha shyam jain
191   23545        20.0  finished                      Rakesh Desai
192   23544        84.0  finished               jitendra kumar giri
193   23543        28.0  finished                     Shivam Tiwari
194   23542       217.0  finished                 shivanee tripathy
195   23541        84.0  finished                  shruthi d kamath
197   23539        22.0  finished                       kusum  jain
199   23537        74.0  finished                 Niraj anil tiwari
200   23536       182.0  finished                            Rupesh
203   23533        22.0  finished                       kusum  jain
208   23528       214.0  finished                     shamim shaik
209   23527        35.0  finished                              Alex
210   23526       206.0  finished             bhaskar roy chowdhury
213   23523       184.0  finished                   gaurav bhansali
214   23522       181.0  finished                             Navin
216   23520        59.0  finished                      Nishat Patil
218   23518        70.0  finished          Shashi Prakash Tripathi
221   23515        92.0  finished               balu ramdas kudekar
222   23514       181.0  finished                         Sakthivel
223   23513       210.0  finished                    Rajendra Salvi
225   23511       217.0  finished                            Pratul
226   23510       242.0  finished           Madhav Narayan Aarotale
229   23507       146.0  finished                sandip ashok mane
230   23506       181.0  finished                         Raju Jhon
237   23499       157.0  finished                     Ramraj Moolya
238   23498       114.0  finished                  VijayKumar gelat
240   23496       187.0  finished                    abhishek kumar
241   23495        20.0  finished                       N.R Nakhare
242   23494       219.0  finished                              Alex
243   23493        35.0  finished                      Amruta Shaha
249   23487       146.0  finished              PrashanT Sopan Patil
250   23486        81.0  finished                             Komal
251   23485       104.0  finished                   Alimiya Miranda
252   23484        20.0  finished                       N.R Nakhare
253   23483       106.0  finished                               NaN
255   23481       206.0  finished                Shashikant gaikwad
256   23480       117.0  finished                   Tanaji bhansode
259   23477       243.0  finished                  Yogesh aakoshkar
260   23476       187.0  finished                   Krishna Marathe
261   23475       222.0  finished              asif ali  afsar ali
262   23474       162.0  finished                               NaN
263   23473       182.0  finished                            Suresh
267   23469       193.0  finished                     Praveen Kumar
270   23466       241.0  finished                              Amol
271   23465       182.0  finished                            Suresh
275   23461       114.0  finished                          Brahmdev
276   23460       206.0  finished                   Arun Pendharkar
278   23458       117.0  finished                             Ninad
280   23456       193.0  finished                     Praveen Kumar
283   23453       193.0  finished                     Praveen Kumar
285   23451       222.0  finished                     Shivam Tiwari
287   23449       193.0  finished                     Praveen Kumar
290   23446       193.0  finished                     Praveen Kumar
292   23444       106.0  finished                        Balu Sathe
298   23438       106.0  finished                          Raj Iyer
301   23435       227.0  finished            anil madhukar nichite
303   23433        60.0  finished                            Rupesh
306   23430         6.0  finished          akash muralidhar khilari
309   23427       131.0  finished         vikas pandurang kulkarni
310   23426       207.0  finished                      Mayur Gawade
311   23425        59.0  finished                             soham
313   23423        81.0  finished           Madhav Narayan Aarotale
316   23420        81.0  finished           Madhav Narayan Aarotale
317   23419       184.0  finished                     Ramraj Moolya
318   23418       115.0  finished                       bablu gupta
321   23415        79.0  finished         chandrakala mahendra sing
323   23413        22.0  finished                 kaveen mike medis
324   23412       114.0  finished                          Brahmdev
325   23411       215.0  finished           supriya shantanu chobhe
326   23410        79.0  finished         chandrakala mahendra sing
327   23409       104.0  finished                      Vikram Meena
328   23408       231.0  finished           supriya shantanu chobhe
329   23407       206.0  finished                      Naresh Gupta
330   23406        35.0  finished                         Omprakash
331   23405       104.0  finished                      Naresh Gupta
332   23404       206.0  finished                     sonal agarwal
334   23402        35.0  finished                      Vikas Tiwari
336   23400        79.0  finished                shreekant salunkhe
337   23399         6.0  finished                             Aarti
338   23398       146.0  finished             milind sudhakar joshi
340   23396       154.0  finished                   gaurav bhansali
341   23395       153.0  finished                     Ankit THAKUR
342   23394        28.0  finished                 Chandramani kumar
345   23391         6.0  finished                    praveen jolly
350   23386       217.0  finished             jayesh sopan phadtare
351   23385        35.0  finished                    Amol Chaudhary
356   23380        28.0  finished                 Chandramani kumar
357   23379       146.0  finished              geeta ganesh vidwans
359   23377       106.0  finished                   Dharamraj Yadav
360   23376       157.0  finished                       nitin joshi
361   23375       241.0  finished             milind sudhakar joshi
362   23374       206.0  finished           nitin arvindbhai mavani
364   23372        35.0  finished                     Harjeet Singh
365   23371       104.0  finished                Arun umanath ullal
366   23370       153.0  finished                             soham
367   23369       206.0  finished           nitin arvindbhai mavani
368   23368       231.0  finished                 nilima arun ullal
369   23367       104.0  finished                Arun umanath ullal
370   23366       154.0  finished               jitendra kumar giri
371   23365       117.0  finished                        Vivekanand
372   23364       104.0  finished                Arun umanath ullal
373   23363       221.0  finished      sanwad shree prakash  sapre
374   23362       184.0  finished       gayadin mahadev vishwakarma
375   23361        79.0  finished                               NaN
376   23360       231.0  finished                Arun umanath ullal
379   23357       206.0  finished                 nilima arun ullal
381   23355       131.0  finished                  Yogesh aakoshkar
383   23353       243.0  finished                             Vipul
386   23350         6.0  finished                             Umesh
387   23349        14.0  finished                 raksha shyam jain
388   23348        22.0  finished                      Mahesh Golap
390   23346       114.0  finished                        atul patil
392   23344       184.0  finished                      Joel Shelton
393   23343         6.0  finished       dileep kumar krishna nayak
394   23342        25.0  finished           priyanka pankaj gonjari
395   23341       153.0  finished                            Rupesh
401   23335         6.0  finished                             Purvi
402   23334        92.0  finished              vandana kisan gawade
406   23330       188.0  finished                 arti sanjay gupta
409   23327       188.0  finished                 arti sanjay gupta
411   23325        35.0  finished                  Fernandes Alston
413   23323       154.0  finished                       kusum  jain
416   23320       105.0  finished                       bablu gupta
418   23318        65.0  finished                   gaurav bhansali
420   23316       154.0  finished                       kusum  jain
421   23315       188.0  finished                      Mukesh Patel
427   23309       206.0  finished           nitin arvindbhai mavani
428   23308       100.0  finished                     ganesh m wagh
433   23303       219.0  finished                   Amarnath Nagare
434   23302        14.0  finished                             Komal
435   23301       206.0  finished                           Suresh
437   23299        95.0  finished                      rosy s kale
443   23293       187.0  finished                  rasika v walimbe
445   23291       215.0  finished                 suma latha shetty
446   23290        25.0  finished        ashish kumar rampher patel
449   23287        79.0  finished          jitendra santosh belani
450   23286       151.0  finished                     Santosh Kumar
451   23285       104.0  finished                       prakash ka
454   23282       242.0  finished                    Sailesh Sharma
457   23279        92.0  finished                               NaN
458   23278        14.0  finished                  santosh Hambarde
459   23277       151.0  finished                             soham
461   23275       231.0  finished                   Arun Pendharkar
462   23274        95.0  finished                             soham
463   23273         6.0  finished                        Amay kadam
464   23272        97.0  finished                              Amol
466   23270       231.0  finished                   Arun Pendharkar
467   23269       206.0  finished                  jayesh waghmare
468   23268       188.0  finished                            Akshat
469   23267       242.0  finished                        Amay kadam
471   23265       106.0  finished                     ALISHA KAMBLE
473   23263       115.0  finished                     Shivam Tiwari
474   23262       151.0  finished                       kusum  jain
490   23246       115.0  finished                     Shivam Tiwari
492   23244       234.0  finished           sumit parmanand sharma
498   23238       117.0  finished                  santosh Hambarde
499   23237       229.0  finished                     Shivam Tiwari
503   23233       191.0  finished                            yaseen
504   23232       229.0  finished            hitesh pandit shevale
506   23230         4.0  finished                  shruthi d kamath
507   23229        84.0  finished          jitendra santosh belani
508   23228        25.0  finished                            Suresh
510   23226         4.0  finished                        Kannadambe
512   23224       242.0  finished                        Amay kadam
518   23218       206.0  finished                     sonal agarwal
521   23215       239.0  finished             Jalpa yagnesh sachdev
527   23209       206.0  finished                         shobhana
528   23208        35.0  finished                      madhu sharma
529   23207        57.0  finished       sandesh harishchandra patil
530   23206       234.0  finished               muskan siraj memon
531   23205       201.0  finished        gundappa basavaraj tarapur
535   23201       242.0  finished                    ramchand parab
540   23196       231.0  finished                  Annuradha  Shahi
548   23188       244.0  finished              geeta ganesh vidwans
550   23186       135.0  finished                        kchma Raul
551   23185       242.0  finished                       nitin joshi
553   23183        59.0  finished                       nitin joshi
554   23182       206.0  finished           rahul pratap sinha rane
556   23180        56.0  finished                               NaN
558   23178       135.0  finished                             Sagar
560   23176        70.0  finished                            Ashish
561   23175       201.0  finished               sunil kumar trivedi
564   23172       188.0  finished                     babita mishra
565   23171        57.0  finished               swati anmol gondane
570   23166       243.0  finished                    Mahesh Sansare
572   23164       201.0  finished               Murli Manohar Singh
573   23163       244.0  finished                    Vineet Gokhale
574   23162        35.0  finished                      neeraj kumar

,ID,Vehicle ID,Status,Member,Member ID,Duration,Fare,Started at,Finished at,Member Type,Starting Parking Station Name,End Parking Station Name,Ride Distance,Starting Parking lot id,End Parking lot id,Month,Year
0,23737,28.0,finished,anjum shaik,11154,0:10:53,0,2019-01-13 21:22:00,2019-01-13 21:33:00,casual_user,"Yashodhan Nagar, Vartak Nagar, ठाणे, Thane, Ma...",R-Mall,1.9,NaN,15.0,1,2019
1,23736,107.0,finished,shruthi d kamath,11689,0:21:58,0,2019-01-13 21:15:00,2019-01-13 21:37:00,casual_user,"Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",Highland Park,2.3,NaN,18.0,1,2019
2,23735,22.0,finished,Ankit THAKUR,13558,0:09:38,0,2019-01-13 21:12:00,2019-01-13 21:22:00,casual_user,"Service Road, Kolse Wadi, Majiwada, ठाणे, Than...","Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",3.1,NaN,NaN,1,2019
4,23733,158.0,finished,asmita kadam,13761,0:24:08,0,2019-01-13 21:07:00,2019-01-13 21:31:00,casual_user,"Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",Highland Park,3.6,NaN,18.0,1,2019
5,23732,107.0,finished,Rohan D kamath,11640,0:24:07,0,2019-01-13 20:50:00,2019-01-13 21:14:00,casual_user,"Dhokali Road, Kolse Wadi, Kapur Bawadi, ठाणे, ...","Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",3.5,NaN,NaN,1,2019
6,23731,244.0,finished,Harish Nair,7846,0:55:35,10,2019-01-13 20:42:00,2019-01-13 21:37:00,casual_user,Tata Sirien,Tata Sirien,1.0,6.0,6.0,1,2019
9,23728,21.0,finished,Tanvi,8938,1:04:58,25,2019-01-13 20:32:00,2019-01-13 21:37:00,casual_user,Tata Sirien,Kashinath Ghanekar,2.3,6.0,10.0,1,2019
11,23726,105.0,finished,suma latha shetty,8800,0:16:56,0,2019-01-13 20:21:00,2019-01-13 20:38:00,casual_user,"Ashar Tiara, Pokhran Road 2, Kolse Wadi, Majiw...",Tata Sirien,2.2,NaN,6.0,1,2019
12,23725,106.0,finished,Shweta Ambade,3343,0:13:17,0,2019-01-13 20:19:00,2019-01-13 20:32:00,casual_user,"Upvan Lake Road, Yashodhan Nagar, Shivai Nagar...",Vartak Nagar,1.7,NaN,2.0,1,2019
13,23724,153.0,finished,Rahul Sonsale,7796,0:08:48,0,2019-01-13 20:14:00,2019-01-13 20:23:00,casual_user,Vartak Nagar,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",1.5,2.0,NaN,1,2019
16,23721,64.0,finished,rhea duseja,11609,0:02:53,0,2019-01-13 20:00:00,2019-01-13 20:02:00,casual_user,"Vartak Nagar, ठाणे, Thane, Maharashtra, 400610...",Vasant Vihar,0.1,NaN,9.0,1,2019
18,23719,186.0,finished,pradeep balkrishna shinde,13300,0:12:11,0,2019-01-13 19:55:00,2019-01-13 20:07:00,casual_user,EEH Panchpakadi Entrence,"Eastern Express Highway, Dnyaneshwar Nagar, Na...",0.9,21.0,NaN,1,2019
19,23718,239.0,finished,bhavisha vikram doevkar,13504,0:19:13,0,2019-01-13 19:50:00,2019-01-13 20:09:00,casual_user,Tata Sirien,Tata Sirien,1.4,6.0,6.0,1,2019
20,23717,158.0,finished,kusum jain,11037,0:38:27,10,2019-01-13 19:47:00,2019-01-13 20:25:00,casual_user,"Agra Road, Kolse Wadi, Kapur Bawadi, ठाणे, Tha...","Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",3.3,NaN,NaN,1,2019
21,23716,176.0,finished,Rajendra Salvi,5671,0:09:12,0,2019-01-13 19:46:00,2019-01-13 19:56:00,casual_user,Shivai Nagar,Singhania School,1.2,14.0,3.0,1,2019
24,23713,112.0,finished,pradeep balkrishna shinde,13300,0:16:59,0,2019-01-13 19:36:00,2019-01-13 19:53:00,casual_user,"Service Road, Dnyaneshwar Nagar, Naupada, ठाणे...","Eastern Express Highway, Dnyaneshwar Nagar, Na...",0.1,NaN,NaN,1,2019
26,23711,231.0,finished,Sandeep Vora,13161,0:19:08,0,2019-01-13 19:30:00,2019-01-13 19:49:00,casual_user,Vartak Nagar,Vartak Nagar,2.4,2.0,2.0,1,2019
27,23710,158.0,finished,kusum jain,11037,0:22:33,0,2019-01-13 19:24:00,2019-01-13 19:46:00,casual_user,"Chendani Koliwada, Thane West, ठाणे, Thane, Ma...","Agra Road, Kolse Wadi, Kapur Bawadi, ठाणे, Tha...",3.5,NaN,NaN,1,2019
28,23709,117.0,finished,Piyush kumar raval,10484,0:20:49,0,2019-01-13 19:21:00,2019-01-13 19:41:00,casual_user,"Happy Valley Homes, Gladys Alwares Road, Kolse...","Happy Valley Homes, Gladys Alwares Road, Kolse...",2.8,NaN,NaN,1,2019
29,23708,70.0,finished,vikas pandurang kulkarni,13297,0:20:49,0,2019-01-13 19:18:00,2019-01-13 19:39:00,casual_user,Patlipada,Patlipada,3.1,12.0,12.0,1,2019
31,23706,77.0,finished,jitendra kumar giri,10520,3:08:14,85,2019-01-13 19:15:00,2019-01-13 22:23:00,casual_user,Yashashvi Nagar,"Pipeline Road, Kolse Wadi, Kapur Bawadi, ठाणे,...",3.8,19.0,NaN,1,2019
32,23704,201.0,finished,shamim shaik,13079,1:01:31,25,2019-01-13 19:13:00,2019-01-13 20:15:00,casual_user,"Hiranandani Estate, Brahmand Nagar, ठाणे, Than...",Patlipada,5.6,NaN,12.0,1,2019
33,23703,153.0,finished,Sandeep Vora,13161,0:17:19,0,2019-01-13 19:11:00,2019-01-13 19:29:00,casual_user,Vartak Nagar,Vartak Nagar,0.9,2.0,2.0,1,2019
36,23700,107.0,finished,NaN,12874,0:05:52,0,2019-01-13 19:00:00,2019-01-13 19:06:00,casual_user,"Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",Highland Park,0.7,NaN,18.0,1,2019
38,23698,107.0,finished,NaN,12874,0:04:45,0,2019-01-13 18:49:00,2019-01-13 18:54:00,casual_user,"Dhokali Road, Kolse Wadi, Kapur Bawadi, ठाणे, ...","Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",0.7,NaN,NaN,1,2019
39,23697,131.0,finished,sunil kumar trivedi,12198,0:23:57,0,2019-01-13 18:49:00,2019-01-13 19:13:00,subscribed_user,"Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...","Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...",3.9,NaN,NaN,1,2019
40,23696,77.0,finished,jitendra kumar giri,10520,0:28:26,0,2019-01-13 18:45:00,2019-01-13 19:13:00,casual_user,"Dhokali Road, Kolse Wadi, Kapur Bawadi, ठाणे, ...",Yashashvi Nagar,4.8,NaN,19.0,1,2019
45,23691,176.0,finished,Rajendra Salvi,5671,0:05:20,0,2019-01-13 18:40:00,2019-01-13 18:45:00,casual_user,Vartak Nagar,"Upvan Lake Road, Yashodhan Nagar, Shivai Nagar...",0.8,2.0,NaN,1,2019
50,23686,74.0,finished,Praveen Kumar,7343,0:22:19,0,2019-01-13 18:29:00,2019-01-13 18:52:00,casual_user,"Service road, Brahmand Nagar, ठाणे, Thane, Mah...",Goodwin Jewellers,4.5,NaN,22.0,1,2019
51,23685,222.0,finished,Shivam Tiwari,12222,0:04:55,0,2019-01-13 18:24:00,2019-01-13 18:29:00,casual_user,Majiwada,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",1.0,5.0,NaN,1,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2115,21621,238.0,finished,abhishek yadavendra yadav,10964,0:22:32,0,2019-01-01 17:55:00,2019-01-01 18:18:00,casual_user,Tata Sirien,"Yashodhan Nagar, Vartak Nagar, ठाणे, Thane, Ma...",0.3,6.0,NaN,1,2019
2116,21620,22.0,finished,shivam,13000,0:06:43,0,2019-01-01 17:52:00,2019-01-01 17:59:00,casual_user,"Vandana ST Bus Depot, LBS Marg, Parshi Wadi, N...","Vandana ST Bus Depot, LBS Marg, Parshi Wadi, N...",0.7,NaN,NaN,1,2019
2117,21619,65.0,finished,NaN,9806,0:24:11,0,2019-01-01 17:50:00,2019-01-01 18:14:00,casual_user,Collector's Office,Collector's Office,2.7,27.0,27.0,1,2019
2123,21613,238.0,finished,abhishek yadavendra yadav,10964,0:27:44,0,2019-01-01 17:27:00,2019-01-01 17:54:00,casual_user,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",Tata Sirien,1.2,NaN,6.0,1,2019
2124,21612,225.0,finished,Sachin,9224,0:23:22,0,2019-01-01 17:23:00,2019-01-01 17:46:00,casual_user,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...","Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",0.1,NaN,NaN,1,2019
2136,21600,45.0,finished,Rasita Sjeen,11605,0:56:57,10,2019-01-01 16:18:00,2019-01-01 17:15:00,casual_user,Highland Park,Highland Park,2.6,18.0,18.0,1,2019
2142,21594,63.0,finished,Niraj anil tiwari,9909,0:17:29,0,2019-01-01 15:08:00,2019-01-01 15:25:00,casual_user,"Eastern Express Highway, Kolse Wadi, Majiwada,...",Shivai Nagar,2.1,NaN,14.0,1,2019
2146,21590,181.0,finished,santosh Hambarde,12567,0:14:35,0,2019-01-01 13:13:00,2019-01-01 13:27:00,casual_user,"Yashodhan Nagar, Lokmanya Nagar, ठाणे, Thane, ...","Ahilyadevi Holkar Marg, Chendani Koliwada, Tha...",2.4,NaN,NaN,1,2019
2147,21589,69.0,finished,Reetu,11987,0:12:34,0,2019-01-01 12:46:00,2019-01-01 12:59:00,subscribed_user,Vasant Vihar,"Happy Valley Homes, Gladys Alwares Road, Kolse...",1.7,9.0,NaN,1,2019
2153,21583,69.0,finished,Reetu,11987,0:05:50,0,2019-01-01 12:14:00,2019-01-01 12:20:00,subscribed_user,"Happy Valley Homes, Gladys Alwares Road, Kolse...","Vartak Nagar, ठाणे, Thane, Maharashtra, 400610...",1.1,NaN,NaN,1,2019
2155,21581,10.0,finished,Amarnath Nagare,8161,5:18:17,145,2019-01-01 12:01:00,2019-01-01 17:19:00,casual_user,"Raigad Aali Marg, Dnyaneshwar Nagar, Naupada, ...","Ram Maruti Road, Parshi Wadi, Naupada, ठाणे, T...",0.6,NaN,NaN,1,2019
2157,21579,35.0,finished,Shrirang dabhade,12781,0:55:06,10,2019-01-01 11:42:00,2019-01-01 12:37:00,casual_user,"Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...","Hiranandani Estate, Brahmand Nagar, ठाणे, Than...",7.5,NaN,NaN,1,2019
2158,21578,45.0,finished,Mithun,12382,0:23:15,0,2019-01-01 11:26:00,2019-01-01 11:49:00,casual_user,"Dhokali Road, Kolse Wadi, Kapur Bawadi, ठाणे, ...",Highland Park,4.4,NaN,18.0,1,2019
2159,21577,63.0,finished,Niraj anil tiwari,9909,0:13:57,0,2019-01-01 11:11:00,2019-01-01 11:25:00,casual_user,"Upvan Lake Road, Yashodhan Nagar, Shivai Nagar...","Service Road, Kolse Wadi, Majiwada, ठाणे, Than...",2.1,NaN,NaN,1,2019
2160,21576,35.0,finished,yogesh madhav bhave,8432,0:35:38,10,2019-01-01 09:16:00,2019-01-01 09:52:00,casual_user,Patlipada,"Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...",3.0,12.0,NaN,1,2019
2165,21571,175.0,finished,Santosh,10766,1:37:24,25,2019-01-01 08:48:00,2019-01-01 10:25:00,casual_user,"Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...","Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...",0.3,NaN,NaN,1,2019
2167,21569,224.0,finished,NaN,4569,0:13:09,0,2019-01-01 08:30:00,2019-01-01 08:43:00,casual_user,Kashinath Ghanekar,"Happy Valley Homes, Gladys Alwares Road, Kolse...",0.5,10.0,NaN,1,2019
2172,21564,175.0,finished,sunil kumar trivedi,12198,0:12:23,0,2019-01-01 08:10:00,2019-01-01 08:23:00,subscribed_user,"Hiranandani Estate, Brahmand Nagar, ठाणे, Than...",Patlipada,2.1,NaN,12.0,1,2019
2173,21563,181.0,finished,Ajit Kanade,11563,0:17:30,0,2019-01-01 08:05:00,2019-01-01 08:22:00,subscribed_user,Vartak Nagar,Vartak Nagar,2.9,2.0,2.0,1,2019
2174,21562,243.0,finished,sanjay Singh,9113,0:23:52,0,2019-01-01 07:52:00,2019-01-01 08:16:00,casual_user,"Pokhran Road 1, Dnyaneshwar Nagar, Vartak Naga...",Vartak Nagar,4.4,NaN,2.0,1,2019
2175,21561,114.0,finished,sandhya Parmeshwar,12740,0:44:25,10,2019-01-01 07:36:00,2019-01-01 08:20:00,casual_user,"Vartak Nagar, ठाणे, Thane, Maharashtra, 400610...","Vartak Nagar, ठाणे, Thane, Maharashtra, 400610...",5.5,NaN,NaN,1,2019
2176,21560,14.0,finished,Harshad ganesh kachhara,9225,0:13:41,0,2019-01-01 07:36:00,2019-01-01 07:49:00,casual_user,Kashinath Ghanekar,Kashinath Ghanekar,1.1,10.0,10.0,1,2019
2177,21559,224.0,finished,nilima arun ullal,12776,0:32:18,10,2019-01-01 07:26:00,2019-01-01 07:58:00,casual_user,Kashinath Ghanekar,Kashinath Ghanekar,4.1,10.0,10.0,1,2019
2179,21557,102.0,finished,Meena Arora,11659,0:18:26,0,2019-01-01 07:23:00,2019-01-01 07:42:00,casual_user,Kashinath Ghanekar,Kashinath Ghanekar,3.0,10.0,10.0,1,2019
2180,21556,129.0,finished,Visalam,12602,0:59:02,10,2019-01-01 07:01:00,2019-01-01 08:00:00,casual_user,"Patlipada RTO, Thane Ghodbunder Road, Brahmand...","Patlipada RTO, Thane Ghodbunder Road, Brahmand...",7.2,NaN,NaN,1,2019
2182,21554,69.0,finished,nitin arvindbhai mavani,11255,0:16:33,0,2019-01-01 06:54:00,2019-01-01 07:10:00,casual_user,Kashinath Ghanekar,"SBI, Gladys Alwares Road, Kolse Wadi, Vartak N...",3.4,10.0,NaN,1,2019
2183,21553,114.0,finished,shakuntala raju nishad,10798,0:02:57,0,2019-01-01 06:45:00,2019-01-01 06:48:00,casual_user,"Vartak Nagar, ठाणे, Thane, Maharashtra, 400610...",Vasant Vihar,0.1,NaN,9.0,1,2019
2184,21552,181.0,finished,Sambhaji Hambarde,12839,1:41:37,25,2019-01-01 06:14:00,2019-01-01 07:56:00,casual_user,Vartak Nagar,Vartak Nagar,0.1,2.0,2.0,1,2019
2185,21551,196.0,finished,sushil pramoid talathi,11914,9:19:54,325,2019-01-01 06:03:00,2019-01-01 15:23:00,subscribed_user,NaN,Yashashvi Nagar,4.1,NaN,19.0,1,2019
2186,21550,181.0,finished,Sambhaji Hambarde,12839,0:11:24,0,2019-01-01 06:01:00,2019-01-01 06:12:00,casual_user,"Chendani Koliwada, Thane West, ठाणे, Thane, Ma...",Vartak Nagar,2.4,NaN,2.0,1,2019

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6195 entries, 0 to 14001
Data columns (total 15 columns):
ID                               6195 non-null int64
Vehicle ID                       5809 non-null float64
Status                           6195 non-null object
Member                           5867 non-null object
Member ID                        6195 non-null int64
Duration                         6195 non-null object
Fare                             6195 non-null int64
Started at                       6195 non-null datetime64[ns]
Finished at                      6195 non-null datetime64[ns]
Member Type                      6195 non-null object
Starting Parking Station Name    5736 non-null object
End Parking Station Name         5716 non-null object
Ride Distance                    6124 non-null float64
Starting Parking lot id          4263 non-null float64
End Parking lot id               4413 non-null float64
dtypes: datetime64[ns](2), float64(4), int64(3), object(6)
memory usage: 774.4+ KB

In [29]:
#df1.tail()

In [16]:
df1['Month'] = pd.DatetimeIndex(df1['Started at']).month

In [17]:
df1['Year'] = pd.DatetimeIndex(df1['Started at']).year

In [30]:
#df1.loc[df1.Year==2019]

In [31]:
#grouped = df1.groupby('Year')

#for name,group in grouped:
        #print(name)
        #print(group)

In [32]:
#df18 = grouped['Member','ID'].get_group(2018)
#df18

In [21]:
#df18 = df1.sort_values(by=['Ride Distance'],ascending = False)

In [33]:
#df18['Member ID'].mode()

In [34]:
#group1 = df1.groupby(['Year','Month','Member ID'])

### Finding top 3 users for every month

In [53]:
group1 = df1.groupby(['Year','Month','Member ID']).agg({'ID': 'count', 'Ride Distance': np.sum,'Fare': np.sum})
group1.sort_values('ID',ascending = False).sort_index(level = [0],ascending = [True]).sort_index(level = [1],ascending = [True]).reset_index(level=[2])

            Member ID  ID  Ride Distance  Fare
Year Month
2018 1           7343  10          19.37    35
     1           7798   5           1.15     0
     1           1840   5          11.34    35
     1           7369   4           8.54     0
     1           9925   3           4.80     0
     1           4037   3           6.40     0
     1           8435   3           0.23     0
     1           7848   3           5.50     0
     1             12   2           0.74     0
     1           1025   2           9.40     0
     1           6821   2           4.30     0
     1           9240   2           3.10     0
     1           6073   2           6.00   525
     1           8931   2           4.50     0
     1           5671   2           5.30     0
     1           7863   2           4.60     0
     1           9807   2           0.60     0
     1           9849   2           3.30    10
     1           9008   2           3.60     0
     1           9923   2           4.80     0
     1           7916   2           5.10    10
     1           7952   2           0.40     0
     1           8008   2           1.44     0
     1           8257   2           3.10    45
     1           8415   2           3.83     0
     1           8591   2           8.00    35
     1           9504   2           3.70     0
     1           7834   2           3.12    10
     1           4867   2           2.84     0
     1           9990   2           2.50     0
...               ...  ..            ...   ...
2019 12         13079   1           0.10     0
     12         13262   1           3.50     0
     12         12140   1           4.60    25
     12         13296   1           3.60     0
     12         13297   1           4.10   325
     12         13383   1           5.90    25
     12         13548   1           3.50     0
     12         13558   1           2.20     0
     12         13596   1           5.00    45
     12         13646   1           1.30     0
     12         13657   1           2.60     0
     12         13665   1           1.40     0
     12         12267   1           2.10     0
     12         12122   1           0.10     0
     12          9561   1           3.00     0
     12          9909   1           0.10     0
     12         10003   1           7.60    85
     12         10040   1           2.30     0
     12         10458   1           4.00     0
     12         10868   1           3.50     0
     12         10957   1           3.80     0
     12         10987   1           0.10     0
     12         11641   1           1.30     0
     12         12105   1           4.10     0
     12         11689   1           2.20     0
     12         12003   1           6.50   525
     12         12032   1           4.90    10
     12         12033   1           5.20     0
     12         12039   1           2.60     0
     12         13731   1           5.30    45

[2994 rows x 4 columns]

In [ ]:
#df1.head()

In [168]:
group1 = df1.groupby(['Year','Month','Member ID']).agg({'ID': 'count', 'Ride Distance': np.sum,'Fare': np.sum})
group1.sort_values('ID',ascending = False).sort_index(level = [0,1],ascending = [True,True]).reset_index(level = [1,2]).groupby(['Year','Month']).head(3)

      Month  Member ID  ID  Ride Distance  Fare
Year
2018      1       7343  10          19.37    35
2018      1       7798   5           1.15     0
2018      1       1840   5          11.34    35
2018      2       7369   7          12.08     0
2018      2       1840   4          15.21     0
2018      2       7798   3           2.29     0
2018      3       7798  15          11.53    10
2018      3       7996   9           8.73     0
2018      3       7803   7           5.22     0
2018      4       7781  12          15.02   550
2018      4       7798  10           3.53    45
2018      4       7882   6           0.44     0
2018      5       7798  18           4.49    10
2018      5       7343   8          12.56    10
2018      5       1840   6          24.01     0
2018      6       7798  10           0.70     0
2018      6       7343   6          11.03    20
2018      6       1840   4          10.44     0
2018      7       5671   6          15.97     0
2018      7       7343   6           8.04     0
2018      7       7369   6          15.36     0
2018      8       7798   6           0.47     0
2018      8       7370   6           6.62    10
2018      8       7796   5           5.10     0
2018      9       7369  17          23.01    30
2018      9       3379  16           1.95     0
2018      9       5671  13          41.85    10
2018     10         12  48          22.37   120
2018     10       1756  44         869.50   505
2018     10       7779  33           5.74   525
...     ...        ...  ..            ...   ...
2019      3      13066   4           6.20    20
2019      3       7798   3           0.50     0
2019      3      11037   3           8.20    10
2019      4      11037   4          15.20    10
2019      4       7343   3           5.30    10
2019      4       4569   3           7.70   525
2019      5      12839   3           7.10     0
2019      5       6073   2           6.40     0
2019      5      12502   2           0.20     0
2019      6       2131   4           9.10     0
2019      6      12480   3           9.10    10
2019      6      13294   2           3.40    85
2019      7       4148   2           1.80     0
2019      7      12567   2           4.40     0
2019      7      12463   2           4.70     0
2019      8       8403   2           4.80     0
2019      8      10907   2           2.40     0
2019      8      11037   2          10.30    35
2019      9       7343  11          17.90     0
2019      9       7804   3           6.80    10
2019      9       8435   3           0.70     0
2019     10       8435   3           0.80     0
2019     10      13436   2           5.00     0
2019     10       5671   2           5.30     0
2019     11      12222   3           3.50     0
2019     11      11037   3           7.70     0
2019     11      12463   3           5.70     0
2019     12       7343   5           9.50     0
2019     12      11137   4           3.90     0
2019     12       7779   3           0.30     0

[72 rows x 5 columns]

In [ ]:
#df2 = (group1.sort_values('ID',ascending = False).sort_index(level = [0],ascending = [True])).sort_index(level = [1],ascending = [True])
#df2

In [ ]:
df = pd.DataFrame({'A': [1, 1, 2, 1, 2],'B': [np.nan, 2, 3, 4, 5]}, columns=['A', 'B'])
g = df.groupby('A')
for key,item in g:
    print(key)
    print(item)

In [ ]:
g.nth(0)

In [ ]:
df = pd.DataFrame({'a': [1, 10, 8, 11, -1], 'b': list('abdce'),'c': [1.0, 2.0, np.nan, 3.0, 4.0]})
df.nlargest(3, 'c')

In [ ]:
df2 = pd.pivot_table(df1,index = ["Year","Month"])
df2.groupby('Member ID').groups

In [ ]:
help(df.reset_index)

In [ ]:
help(df.nlargest)

In [97]:
cf = pd.DataFrame({'year': [2010, 2010, 2010, 2011,2011,2011, 2012, 2012, 2013, 2013, 2014, 2014],
                  'username': ['b','a','a','c','c','d','e','f','g','i','h','j'],
                  'count': [400, 505, 678, 677, 505, 505, 677, 505, 677, 505, 677, 505]})
cf = cf.set_index(['year','username'])
top = 3
cf = cf.groupby(level=0).apply(lambda cf: cf.sort_index(by='count')[-top:])
cf.index = cf.index.droplevel(0)
cf

C:\Users\sapan\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)

               count
year username
2010 b           400
     a           505
     a           678
2011 c           505
     d           505
     c           677
2012 f           505
     e           677
2013 i           505
     g           677
2014 j           505
     h           677

In [167]:
d19 = df1.loc[df1['Year'] == 2019]
d19.loc[d19.Month == 12]

,ID,Vehicle ID,Status,Member,Member ID,Duration,Fare,Started at,Finished at,Member Type,Starting Parking Station Name,End Parking Station Name,Ride Distance,Starting Parking lot id,End Parking lot id,Month,Year
192,23544,84.0,finished,jitendra kumar giri,10520,0:26:01,0,2019-12-01 21:29:00,2019-12-01 21:55:00,casual_user,Highland Park,Highland Park,4.2,18.0,18.0,12,2019
193,23543,28.0,finished,Shivam Tiwari,12222,0:12:18,0,2019-12-01 21:18:00,2019-12-01 21:30:00,casual_user,"Ashar Tiara, Pokhran Road 2, Kolse Wadi, Majiw...",Vartak Nagar,2.6,NaN,2.0,12,2019
194,23542,217.0,finished,shivanee tripathy,13296,0:26:02,0,2019-12-01 21:13:00,2019-12-01 21:39:00,casual_user,Majiwada,"Service Road, Kolse Wadi, Majiwada, ठाणे, Than...",3.6,5.0,NaN,12,2019
195,23541,84.0,finished,shruthi d kamath,11689,0:16:15,0,2019-12-01 21:04:00,2019-12-01 21:20:00,casual_user,"Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",Highland Park,2.2,NaN,18.0,12,2019
197,23539,22.0,finished,kusum jain,11037,0:37:26,10,2019-12-01 21:00:00,2019-12-01 21:37:00,casual_user,"Agra Road, Kolse Wadi, Kapur Bawadi, ठाणे, Tha...","Viviana Mall, Eastern Express Highway, Kolse W...",4.8,NaN,NaN,12,2019
199,23537,74.0,finished,Niraj anil tiwari,9909,0:05:51,0,2019-12-01 20:52:00,2019-12-01 20:58:00,casual_user,"Upvan Lake Road, Yashodhan Nagar, Shivai Nagar...","Upvan Lake Road, Yashodhan Nagar, Shivai Nagar...",0.1,NaN,NaN,12,2019
200,23536,182.0,finished,Rupesh,7798,0:16:01,0,2019-12-01 20:32:00,2019-12-01 20:48:00,casual_user,Singhania School,"Viviana Mall, Eastern Express Highway, Kolse W...",2.3,3.0,NaN,12,2019
203,23533,22.0,finished,kusum jain,11037,0:30:50,10,2019-12-01 20:28:00,2019-12-01 20:59:00,casual_user,"Dhokali Road, Kolse Wadi, Kapur Bawadi, ठाणे, ...","Agra Road, Kolse Wadi, Kapur Bawadi, ठाणे, Tha...",3.6,NaN,NaN,12,2019
208,23528,214.0,finished,shamim shaik,13079,0:13:25,0,2019-12-01 20:05:00,2019-12-01 20:18:00,casual_user,Patlipada,"Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...",0.1,12.0,NaN,12,2019
209,23527,35.0,finished,Alex,10423,14:25:00,525,2019-12-01 19:55:00,2019-01-13 10:20:00,casual_user,Kashinath Ghanekar,"NAVNIT MOTORS, Lal Bahadur Shastri Marg, Kolse...",2.7,10.0,NaN,12,2019
210,23526,206.0,finished,bhaskar roy chowdhury,12032,0:57:48,10,2019-12-01 19:55:00,2019-12-01 20:52:00,casual_user,"Gladys Alwares Road, Kolse Wadi, Vartak Nagar,...","Happy Valley Homes, Gladys Alwares Road, Kolse...",4.9,NaN,NaN,12,2019
213,23523,184.0,finished,gaurav bhansali,4192,0:10:20,0,2019-12-01 19:45:00,2019-12-01 19:55:00,casual_user,Majiwada,"Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",0.9,5.0,NaN,12,2019
214,23522,181.0,finished,Navin,7174,1:46:45,25,2019-12-01 19:40:00,2019-12-01 21:26:00,casual_user,Kashinath Ghanekar,Kashinath Ghanekar,4.3,10.0,10.0,12,2019
216,23520,59.0,finished,Nishat Patil,682,0:15:45,0,2019-12-01 19:36:00,2019-12-01 19:52:00,casual_user,Vartak Nagar,Singhania School,2.0,2.0,3.0,12,2019
218,23518,70.0,finished,Shashi Prakash Tripathi,13383,1:28:08,25,2019-12-01 19:28:00,2019-12-01 20:56:00,casual_user,Patlipada,Patlipada,5.9,12.0,12.0,12,2019
221,23515,92.0,finished,balu ramdas kudekar,12122,0:03:56,0,2019-12-01 19:23:00,2019-12-01 19:27:00,casual_user,Goodwin Jewellers,"Chendani Koliwada, Thane West, ठाणे, Thane, Ma...",0.1,22.0,NaN,12,2019
222,23514,181.0,finished,Sakthivel,6091,0:06:00,0,2019-12-01 19:22:00,2019-12-01 19:28:00,casual_user,Vasant Vihar,Kashinath Ghanekar,0.7,9.0,10.0,12,2019
223,23513,210.0,finished,Rajendra Salvi,5671,0:08:25,0,2019-12-01 19:22:00,2019-12-01 19:31:00,casual_user,"Yashodhan Nagar, Shivai Nagar, ठाणे, Thane, Ma...",Singhania School,1.2,NaN,3.0,12,2019
225,23511,217.0,finished,Pratul,12664,0:08:39,0,2019-12-01 19:11:00,2019-12-01 19:20:00,casual_user,"Service Road, Kolse Wadi, Majiwada, ठाणे, Than...",Majiwada,0.9,NaN,5.0,12,2019
226,23510,242.0,finished,Madhav Narayan Aarotale,7779,0:04:32,0,2019-12-01 19:10:00,2019-12-01 19:14:00,casual_user,"Korum Mall, Service Road, Dnyaneshwar Nagar, N...","Korum Mall, Service Road, Dnyaneshwar Nagar, N...",0.1,NaN,NaN,12,2019
229,23507,146.0,finished,sandip ashok mane,13731,2:11:31,45,2019-12-01 19:01:00,2019-12-01 21:12:00,casual_user,"Happy Valley Homes, Gladys Alwares Road, Kolse...",Kevra Circle,5.3,NaN,11.0,12,2019
230,23506,181.0,finished,Raju Jhon,8436,0:13:34,0,2019-12-01 18:54:00,2019-12-01 19:08:00,casual_user,"Viviana Mall, Eastern Express Highway, Kolse W...",Vasant Vihar,2.3,NaN,9.0,12,2019
237,23499,157.0,finished,Ramraj Moolya,7250,0:11:42,0,2019-12-01 18:42:00,2019-12-01 18:54:00,casual_user,"Eastern Express Highway, Dnyaneshwar Nagar, Na...",Singhania School,1.6,NaN,3.0,12,2019
238,23498,114.0,finished,VijayKumar gelat,12140,1:36:05,25,2019-12-01 18:41:00,2019-12-01 20:17:00,casual_user,Kashinath Ghanekar,Kashinath Ghanekar,4.6,10.0,10.0,12,2019
240,23496,187.0,finished,abhishek kumar,10868,0:21:35,0,2019-12-01 18:40:00,2019-12-01 19:01:00,casual_user,"Agra Road, Kolse Wadi, Kapur Bawadi, ठाणे, Tha...",Goodwin Jewellers,3.5,NaN,22.0,12,2019
241,23495,20.0,finished,N.R Nakhare,1840,0:17:18,0,2019-12-01 18:39:00,2019-12-01 18:57:00,casual_user,"Cosmos Hills, Upvan Lake Road, Yashodhan Nagar...",Shivai Nagar,2.2,NaN,14.0,12,2019
242,23494,219.0,finished,Alex,10423,1:16:10,25,2019-12-01 18:38:00,2019-12-01 19:54:00,casual_user,Vandana Cinema,Kashinath Ghanekar,3.7,20.0,10.0,12,2019
243,23493,35.0,finished,Amruta Shaha,12829,0:28:54,0,2019-12-01 18:33:00,2019-12-01 19:01:00,casual_user,Kashinath Ghanekar,Kashinath Ghanekar,1.0,10.0,10.0,12,2019
249,23487,146.0,finished,PrashanT Sopan Patil,12712,0:19:20,0,2019-12-01 18:25:00,2019-12-01 18:44:00,casual_user,"Gladys Alwares Road, Kolse Wadi, Vartak Nagar,...","Happy Valley Homes, Gladys Alwares Road, Kolse...",2.5,NaN,NaN,12,2019
250,23486,81.0,finished,Komal,13596,2:27:42,45,2019-12-01 18:24:00,2019-12-01 20:52:00,casual_user,Vartak Nagar,Singhania School,5.0,2.0,3.0,12,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,23386,217.0,finished,jayesh sopan phadtare,9393,0:24:05,0,2019-12-01 08:09:00,2019-12-01 08:33:00,casual_user,"Viviana Mall, Eastern Express Highway, Kolse W...","Service Road, Kolse Wadi, Majiwada, ठाणे, Than...",4.6,NaN,NaN,12,2019
351,23385,35.0,finished,Amol Chaudhary,8060,0:23:14,0,2019-12-01 08:08:00,2019-12-01 08:31:00,casual_user,Kashinath Ghanekar,Kashinath Ghanekar,2.8,10.0,10.0,12,2019
356,23380,28.0,finished,Chandramani kumar,10719,0:09:47,0,2019-12-01 08:02:00,2019-12-01 08:12:00,casual_user,Gandhi Nagar,"Ashar Tiara, Pokhran Road 2, Kolse Wadi, Majiw...",1.1,8.0,NaN,12,2019
357,23379,146.0,finished,geeta ganesh vidwans,12593,0:13:23,0,2019-12-01 07:56:00,2019-12-01 08:10:00,casual_user,Tata Sirien,Tata Sirien,0.6,6.0,6.0,12,2019
359,23377,106.0,finished,Dharamraj Yadav,2404,0:16:22,0,2019-12-01 07:53:00,2019-12-01 08:09:00,casual_user,"Korum Mall, Service Road, Dnyaneshwar Nagar, N...",Korum Mall,2.5,NaN,4.0,12,2019
360,23376,157.0,finished,nitin joshi,8526,0:19:41,0,2019-12-01 07:52:00,2019-12-01 08:12:00,casual_user,"Eastern Express Highway, Dnyaneshwar Nagar, Na...","Eastern Express Highway, Dnyaneshwar Nagar, Na...",3.1,NaN,NaN,12,2019
361,23375,241.0,finished,milind sudhakar joshi,11259,0:30:42,10,2019-12-01 07:49:00,2019-12-01 08:19:00,casual_user,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",Tata Sirien,3.9,NaN,6.0,12,2019
362,23374,206.0,finished,nitin arvindbhai mavani,11255,0:19:34,0,2019-12-01 07:47:00,2019-12-01 08:06:00,casual_user,Tata Sirien,"Happy Valley Homes, Gladys Alwares Road, Kolse...",3.5,6.0,NaN,12,2019
364,23372,35.0,finished,Harjeet Singh,9561,0:21:07,0,2019-12-01 07:46:00,2019-12-01 08:07:00,casual_user,"The Origin Fertility Clinic, Gladys Alwares Ro...",Kashinath Ghanekar,3.0,NaN,10.0,12,2019
365,23371,104.0,finished,Arun umanath ullal,11137,0:16:40,0,2019-12-01 07:45:00,2019-12-01 08:02:00,casual_user,"Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...","Gladys Alwares Road, Kolse Wadi, Vartak Nagar,...",3.1,NaN,NaN,12,2019
366,23370,153.0,finished,soham,7804,0:11:09,0,2019-12-01 07:45:00,2019-12-01 07:56:00,casual_user,"Viviana Mall, Eastern Express Highway, Kolse W...","Kolse Wadi, Kapur Bawadi, ठाणे, Thane, Maharas...",1.9,NaN,NaN,12,2019
367,23369,206.0,finished,nitin arvindbhai mavani,11255,0:10:29,0,2019-12-01 07:36:00,2019-12-01 07:46:00,casual_user,"Happy Valley Homes, Gladys Alwares Road, Kolse...",Tata Sirien,2.3,NaN,6.0,12,2019
368,23368,231.0,finished,nilima arun ullal,12776,0:33:37,10,2019-12-01 07:31:00,2019-12-01 08:04:00,casual_user,"Happy Valley Homes, Gladys Alwares Road, Kolse...","Gladys Alwares Road, Kolse Wadi, Vartak Nagar,...",4.1,NaN,NaN,12,2019
369,23367,104.0,finished,Arun umanath ullal,11137,0:10:17,0,2019-12-01 07:28:00,2019-12-01 07:39:00,casual_user,"Happy Valley Homes, Gladys Alwares Road, Kolse...","Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...",0.6,NaN,NaN,12,2019
370,23366,154.0,finished,jitendra kumar giri,10520,0:25:12,0,2019-12-01 07:26:00,2019-12-01 07:51:00,casual_user,"Agra Road, Kolse Wadi, Kapur Bawadi, ठाणे, Tha...","Agra Road, Kolse Wadi, Kapur Bawadi, ठाणे, Tha...",4.5,NaN,NaN,12,2019
371,23365,117.0,finished,Vivekanand,9328,0:26:20,0,2019-12-01 07:26:00,2019-12-01 07:52:00,casual_user,"Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...","Pokhran Road 2, Kolse Wadi, Majiwada, ठाणे, Th...",2.4,NaN,NaN,12,2019
372,23364,104.0,finished,Arun umanath ullal,11137,0:01:53,0,2019-12-01 07:25:00,2019-12-01 07:27:00,casual_user,"SBI, Gladys Alwares Road, Kolse Wadi, Vartak N...","Happy Valley Homes, Gladys Alwares Road, Kolse...",0.1,NaN,NaN,12,2019
373,23363,221.0,finished,sanwad shree prakash sapre,13262,0:24:55,0,2019-12-01 07:23:00,2019-12-01 07:48:00,casual_user,"Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...",Patlipada,3.5,NaN,12.0,12,2019
374,23362,184.0,finished,gayadin mahadev vishwakarma,12039,0:21:24,0,2019-12-01 07:23:00,2019-12-01 07:44:00,casual_user,"Smt. Sulochanadevi Singhania School, Pokhran R...",Singhania School,2.6,NaN,3.0,12,2019
375,23361,79.0,finished,NaN,10957,0:24:05,0,2019-12-01 07:21:00,2019-12-01 07:45:00,subscribed_user,Highland Park,Highland Park,3.8,18.0,18.0,12,2019
376,23360,231.0,finished,Arun umanath ullal,11137,0:03:17,0,2019-12-01 07:21:00,2019-12-01 07:24:00,casual_user,"Happy Valley Homes, Gladys Alwares Road, Kolse...","Happy Valley Homes, Gladys Alwares Road, Kolse...",0.1,NaN,NaN,12,2019
379,23357,206.0,finished,nilima arun ullal,12776,0:11:39,0,2019-12-01 07:19:00,2019-12-01 07:30:00,casual_user,"Happy Valley Homes, Gladys Alwares Road, Kolse...","Happy Valley Homes, Gladys Alwares Road, Kolse...",0.2,NaN,NaN,12,2019
381,23355,131.0,finished,Yogesh aakoshkar,13532,0:54:36,10,2019-12-01 07:16:00,2019-12-01 08:10:00,casual_user,"Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...","Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...",1.9,NaN,NaN,12,2019
383,23353,243.0,finished,Vipul,12105,0:29:41,0,2019-12-01 07:07:00,2019-12-01 07:36:00,casual_user,"Hiranandani Estate, Brahmand Nagar, ठाणे, Than...","Brahmand Nagar, ठाणे, Thane, Maharashtra, 4006...",4.1,NaN,NaN,12,2019
386,23350,6.0,finished,Umesh,10458,0:20:15,0,2019-12-01 06:59:00,2019-12-01 07:20:00,casual_user,"GZ, Govind Bachhaji Road, Kranti Nagar, Thane ...","Gadkari Rangayatan, Dr. Moose Road, Chendani K...",4.0,NaN,NaN,12,2019
387,23349,14.0,finished,raksha shyam jain,8181,0:20:14,0,2019-12-01 06:53:00,2019-12-01 07:13:00,casual_user,Singhania School,Singhania School,3.0,3.0,3.0,12,2019
388,23348,22.0,finished,Mahesh Golap,5685,0:19:07,0,2019-12-01 06:50:00,2019-12-01 07:09:00,casual_user,Highland Park,Highland Park,2.2,18.0,18.0,12,2019
390,23346,114.0,finished,atul patil,12587,0:56:38,10,2019-12-01 06:43:00,2019-12-01 07:40:00,casual_user,Vartak Nagar,Vartak Nagar,4.6,2.0,2.0,12,2019
392,23344,184.0,finished,Joel Shelton,5846,0:17:29,0,2019-12-01 06:34:00,2019-12-01 06:52:00,casual_user,"Lal Bahadur Shastri Marg, Kolse Wadi, Majiwada...",NaN,1.6,NaN,NaN,12,2019
393,23343,6.0,finished,dileep kumar krishna nayak,13657,0:17:25,0,2019-12-01 06:26:00,2019-12-01 06:44:00,casual_user,"Chendani Koliwada, Naupada, ठाणे, Thane, Mahar...","Chendani Koliwada, Thane West, ठाणे, Thane, Ma...",2.6,NaN,NaN,12,2019